version: "3.8"

services:
  typesense:
    image: typesense/typesense:27.1
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY:-xyz123}
      - TYPESENSE_DATA_DIR=/data
    restart: unless-stopped
